#!/bin/bash
#SBATCH --time=10:30:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --mem=8000
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=marloes.madelon@gmail.com
module load Python/3.6.4-foss-2018a

python word_embedding_experiment.py -cross -name "results_cross_genre_native_lang_tm_word_embedding_experiment_regular_25D.txt" -data_file "../my_data2/data_final_cross_genre_native_lang_tm.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type regular -dim 25
python word_embedding_experiment.py -cross -name "results_cross_genre_native_lang_mt_word_embedding_experiment_regular_25D.txt" -data_file "../my_data2/data_final_cross_genre_native_lang_mt.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type regular -dim 25
python word_embedding_experiment.py -name "results_within_genre_native_lang_twitter_word_embedding_experiment_regular_25D.txt" -data_file "../my_data2/data_final_within_genre_native_lang_twitter.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type regular -dim 25
python word_embedding_experiment.py -name "results_within_genre_native_lang_medium_word_embedding_experiment_regular_25D.txt" -data_file "../my_data2/data_final_within_genre_native_lang_medium.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type regular -dim 25
python word_embedding_experiment.py -cross --gender -name "results_cross_genre_gender_tm_word_embedding_experiment_regular_25D.txt" -data_file "../my_data2/data_final_cross_genre_gender_tm.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type regular -dim 25
python word_embedding_experiment.py -cross --gender -name "results_cross_genre_gender_mt_word_embedding_experiment_regular_25D.txt" -data_file "../my_data2/data_final_cross_genre_gender_mt.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type regular -dim 25
python word_embedding_experiment.py --gender -name "results_within_genre_gender_twitter_word_embedding_experiment_regular_25D.txt" -data_file "../my_data2/data_final_within_genre_gender_twitter.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type regular -dim 25
python word_embedding_experiment.py --gender -name "results_within_genre_gender_medium_word_embedding_experiment_regular_25D.txt" -data_file "../my_data2/data_final_within_genre_gender_medium.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type regular -dim 25
python word_embedding_experiment.py -cross -name "results_cross_genre_native_lang_tm_word_embedding_experiment_learner_25D.txt" -data_file "../my_data2/data_final_cross_genre_native_lang_tm.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type learner -dim 25
python word_embedding_experiment.py -cross -name "results_cross_genre_native_lang_mt_word_embedding_experiment_learner_25D.txt" -data_file "../my_data2/data_final_cross_genre_native_lang_mt.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type learner -dim 25
python word_embedding_experiment.py -name "results_within_genre_native_lang_twitter_word_embedding_experiment_learner_25D.txt" -data_file "../my_data2/data_final_within_genre_native_lang_twitter.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type learner -dim 25
python word_embedding_experiment.py -name "results_within_genre_native_lang_medium_word_embedding_experiment_learner_25D.txt" -data_file "../my_data2/data_final_within_genre_native_lang_medium.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type learner -dim 25
python word_embedding_experiment.py -cross --gender -name "results_cross_genre_gender_tm_word_embedding_experiment_learner_25D.txt" -data_file "../my_data2/data_final_cross_genre_gender_tm.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type learner -dim 25
python word_embedding_experiment.py -cross --gender -name "results_cross_genre_gender_mt_word_embedding_experiment_learner_25D.txt" -data_file "../my_data2/data_final_cross_genre_gender_mt.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type learner -dim 25
python word_embedding_experiment.py --gender -name "results_within_genre_gender_twitter_word_embedding_experiment_learner_25D.txt" -data_file "../my_data2/data_final_within_genre_gender_twitter.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type learner -dim 25
python word_embedding_experiment.py --gender -name "results_within_genre_gender_medium_word_embedding_experiment_learner_25D.txt" -data_file "../my_data2/data_final_within_genre_gender_medium.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_25d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B25D.json -type learner -dim 25

python word_embedding_experiment.py -cross -name "results_cross_genre_native_lang_tm_word_embedding_experiment_regular_100D.txt" -data_file "../my_data2/data_final_cross_genre_native_lang_tm.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type regular -dim 100
python word_embedding_experiment.py -cross -name "results_cross_genre_native_lang_mt_word_embedding_experiment_regular_100D.txt" -data_file "../my_data2/data_final_cross_genre_native_lang_mt.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type regular -dim 100
python word_embedding_experiment.py -name "results_within_genre_native_lang_twitter_word_embedding_experiment_regular_100D.txt" -data_file "../my_data2/data_final_within_genre_native_lang_twitter.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type regular -dim 100
python word_embedding_experiment.py -name "results_within_genre_native_lang_medium_word_embedding_experiment_regular_100D.txt" -data_file "../my_data2/data_final_within_genre_native_lang_medium.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type regular -dim 100
python word_embedding_experiment.py -cross --gender -name "results_cross_genre_gender_tm_word_embedding_experiment_regular_100D.txt" -data_file "../my_data2/data_final_cross_genre_gender_tm.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type regular -dim 100
python word_embedding_experiment.py -cross --gender -name "results_cross_genre_gender_mt_word_embedding_experiment_regular_100D.txt" -data_file "../my_data2/data_final_cross_genre_gender_mt.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type regular -dim 100
python word_embedding_experiment.py --gender -name "results_within_genre_gender_twitter_word_embedding_experiment_regular_100D.txt" -data_file "../my_data2/data_final_within_genre_gender_twitter.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type regular -dim 100
python word_embedding_experiment.py --gender -name "results_within_genre_gender_medium_word_embedding_experiment_regular_100D.txt" -data_file "../my_data2/data_final_within_genre_gender_medium.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type regular -dim 100
python word_embedding_experiment.py -cross -name "results_cross_genre_native_lang_tm_word_embedding_experiment_learner_100D.txt" -data_file "../my_data2/data_final_cross_genre_native_lang_tm.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type learner -dim 100
python word_embedding_experiment.py -cross -name "results_cross_genre_native_lang_mt_word_embedding_experiment_learner_100D.txt" -data_file "../my_data2/data_final_cross_genre_native_lang_mt.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type learner -dim 100
python word_embedding_experiment.py -name "results_within_genre_native_lang_twitter_word_embedding_experiment_learner_100D.txt" -data_file "../my_data2/data_final_within_genre_native_lang_twitter.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type learner -dim 100
python word_embedding_experiment.py -name "results_within_genre_native_lang_medium_word_embedding_experiment_learner_100D.txt" -data_file "../my_data2/data_final_within_genre_native_lang_medium.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type learner -dim 100
python word_embedding_experiment.py -cross --gender -name "results_cross_genre_gender_tm_word_embedding_experiment_learner_100D.txt" -data_file "../my_data2/data_final_cross_genre_gender_tm.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type learner -dim 100
python word_embedding_experiment.py -cross --gender -name "results_cross_genre_gender_mt_word_embedding_experiment_learner_100D.txt" -data_file "../my_data2/data_final_cross_genre_gender_mt.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type learner -dim 100
python word_embedding_experiment.py --gender -name "results_within_genre_gender_twitter_word_embedding_experiment_learner_100D.txt" -data_file "../my_data2/data_final_within_genre_gender_twitter.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type learner -dim 100
python word_embedding_experiment.py --gender -name "results_within_genre_gender_medium_word_embedding_experiment_learner_100D.txt" -data_file "../my_data2/data_final_within_genre_gender_medium.csv" -data_folder . -wel_json  ../word_embedding_files/learner_english_embeddings_100d.json -wer_json  ../word_embedding_files/glove_regular_embeddings_27B100D.json -type learner -dim 100
